// ============================================================
// Aayurface — Mock Data Provider
// Complete seed data for 30+ remedies, 30+ daily tips, and mock scan results
// ============================================================

import type { Remedy, DailyTip, ScanResult, ScanCause, ScanRemedy, PreventionTip } from '@/types';

// ============================================================
// REMEDIES (30+ entries)
// ============================================================

export const MOCK_REMEDIES: Remedy[] = [
  {
    id: 'r1',
    name: 'Neem & Turmeric Face Mask',
    slug: 'neem-turmeric-face-mask',
    description: 'A powerful antibacterial mask that fights acne-causing bacteria while reducing inflammation and redness. Neem purifies while turmeric brightens.',
    ingredients: [
      { name: 'Neem powder', amount: '2 tablespoons' },
      { name: 'Turmeric powder', amount: '1/2 teaspoon' },
      { name: 'Rose water', amount: '2 tablespoons' },
      { name: 'Raw honey', amount: '1 teaspoon' },
    ],
    preparation_steps: [
      'Mix neem powder and turmeric in a clean bowl.',
      'Add rose water gradually, stirring to form a smooth paste.',
      'Mix in raw honey for added moisture.',
      'Let the mixture sit for 2 minutes to activate.',
    ],
    application_steps: [
      'Cleanse your face with lukewarm water.',
      'Apply the mask evenly, avoiding the eye area.',
      'Leave on for 15–20 minutes until it dries.',
      'Rinse with cool water in gentle circular motions.',
      'Pat dry and follow with a light moisturizer.',
    ],
    frequency: '2–3 times per week',
    ayurvedic_insight: 'In Ayurveda, neem (Nimba) is revered as a "Sarva Roga Nivarini" — a cure for all ailments. Combined with turmeric (Haridra), it pacifies Pitta and Kapha doshas.',
    skin_concerns: ['Acne', 'Oiliness', 'Redness'],
    skin_types: ['oily', 'combination'],
    image_url: null,
    is_featured: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r2',
    name: 'Aloe Vera & Rose Water Toner',
    slug: 'aloe-vera-rose-water-toner',
    description: 'A refreshing toner that hydrates, tightens pores, and balances skin pH naturally. Perfect for daily use after cleansing.',
    ingredients: [
      { name: 'Fresh aloe vera gel', amount: '3 tablespoons' },
      { name: 'Rose water', amount: '3 tablespoons' },
      { name: 'Vitamin E oil', amount: '2–3 drops' },
    ],
    preparation_steps: [
      'Extract fresh aloe vera gel from the leaf.',
      'Blend the gel until smooth and strain any pulp.',
      'Mix with rose water in a spray bottle.',
      'Add vitamin E oil and shake well.',
      'Store in the refrigerator for up to one week.',
    ],
    application_steps: [
      'After cleansing, spray or apply with a cotton pad.',
      'Gently pat into skin — don\'t rub.',
      'Allow to absorb for 1–2 minutes before moisturizer.',
    ],
    frequency: 'Twice daily (morning & evening)',
    ayurvedic_insight: 'Aloe vera (Kumari) is a tridoshic herb — it balances Vata, Pitta, and Kapha. Rose water (Gulab Jal) is cooling and soothing, ideal for calming Pitta.',
    skin_concerns: ['Oiliness', 'Dryness', 'Redness'],
    skin_types: ['oily', 'combination', 'normal'],
    image_url: null,
    is_featured: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r3',
    name: 'Kumkumadi Brightening Oil',
    slug: 'kumkumadi-brightening-oil',
    description: 'A luxurious Ayurvedic facial oil made with saffron that reduces dark spots, evens skin tone, and restores natural radiance overnight.',
    ingredients: [
      { name: 'Kumkumadi tailam (oil)', amount: '4–5 drops' },
    ],
    preparation_steps: [
      'This is a ready-made traditional Ayurvedic oil.',
      'Purchase from a trusted Ayurvedic brand.',
      'Ensure it contains genuine saffron (Kumkuma) as a key ingredient.',
    ],
    application_steps: [
      'Warm 4–5 drops between your palms.',
      'Gently massage onto clean face in upward circular motions.',
      'Focus on areas with dark spots or uneven tone.',
      'Leave on overnight for best results.',
    ],
    frequency: 'Every night before bed',
    ayurvedic_insight: 'Kumkumadi Tailam is one of the most revered Ayurvedic formulations, dating back to ancient texts. Saffron (Kumkuma) is considered the ultimate herb for skin radiance and complexion enhancement.',
    skin_concerns: ['Dark Spots', 'Pigmentation', 'Uneven Tone'],
    skin_types: ['dry', 'normal', 'combination'],
    image_url: null,
    is_featured: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r4',
    name: 'Sandalwood & Milk Cleanser',
    slug: 'sandalwood-milk-cleanser',
    description: 'A gentle, creamy cleanser that removes impurities while nourishing dry and sensitive skin with cooling sandalwood.',
    ingredients: [
      { name: 'Sandalwood powder', amount: '1 tablespoon' },
      { name: 'Raw milk', amount: '2 tablespoons' },
      { name: 'Pinch of saffron', amount: '2–3 strands' },
    ],
    preparation_steps: [
      'Soak saffron strands in milk for 10 minutes.',
      'Add sandalwood powder and mix to form a thin paste.',
    ],
    application_steps: [
      'Apply to face with gentle upward strokes.',
      'Massage in circular motions for 2–3 minutes.',
      'Rinse with lukewarm water.',
      'Pat dry gently.',
    ],
    frequency: 'Daily (morning cleanser)',
    ayurvedic_insight: 'Sandalwood (Chandana) is one of the most sacred ingredients in Ayurveda. It cools Pitta, soothes inflammation, and has been used for centuries as a beauty ritual.',
    skin_concerns: ['Dryness', 'Redness'],
    skin_types: ['dry', 'sensitive'],
    image_url: null,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r5',
    name: 'Triphala Under-Eye Treatment',
    slug: 'triphala-under-eye-treatment',
    description: 'An Ayurvedic treatment to reduce under-eye circles, puffiness, and fatigue signs using the powerful Triphala trio.',
    ingredients: [
      { name: 'Triphala powder', amount: '1 teaspoon' },
      { name: 'Almond oil', amount: '1 teaspoon' },
      { name: 'Rose water', amount: '1 teaspoon' },
    ],
    preparation_steps: [
      'Mix triphala powder with almond oil.',
      'Add rose water to create a light paste.',
      'Let it sit for 5 minutes.',
    ],
    application_steps: [
      'Gently dab under each eye using your ring finger.',
      'Use the lightest touch possible — the under-eye skin is delicate.',
      'Leave on for 15 minutes.',
      'Rinse with cool water.',
    ],
    frequency: '3–4 times per week',
    ayurvedic_insight: 'Triphala, the "three fruits" formula (Amalaki, Bibhitaki, Haritaki), is a cornerstone of Ayurvedic medicine, known for its rejuvenating and detoxifying properties.',
    skin_concerns: ['Dark Spots', 'Pigmentation'],
    skin_types: ['normal', 'dry', 'combination', 'sensitive'],
    image_url: null,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r6',
    name: 'Ashwagandha Stress Relief Mask',
    slug: 'ashwagandha-stress-relief-mask',
    description: 'A calming face mask that addresses stress-induced skin issues like dullness, breakouts, and premature aging using adaptogenic ashwagandha.',
    ingredients: [
      { name: 'Ashwagandha powder', amount: '1 tablespoon' },
      { name: 'Honey', amount: '1 tablespoon' },
      { name: 'Warm milk', amount: '1 tablespoon' },
    ],
    preparation_steps: [
      'Mix ashwagandha powder with warm milk.',
      'Add honey and blend into a smooth paste.',
    ],
    application_steps: [
      'Apply evenly on clean face.',
      'Relax for 20 minutes — practice deep breathing.',
      'Rinse with lukewarm water.',
    ],
    frequency: '2 times per week',
    ayurvedic_insight: 'Ashwagandha (Withania somnifera) is the premier adaptogen in Ayurveda, known as "Indian Ginseng." It reduces cortisol and combats oxidative stress that accelerates skin aging.',
    skin_concerns: ['Dryness', 'Acne', 'Uneven Tone'],
    skin_types: ['oily', 'dry', 'combination', 'normal', 'sensitive'],
    image_url: null,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r7',
    name: 'Turmeric & Gram Flour Brightening Pack',
    slug: 'turmeric-gram-flour-brightening',
    description: 'A traditional Ubtan recipe that exfoliates, brightens, and brings a natural glow to dull, lifeless skin.',
    ingredients: [
      { name: 'Gram flour (Besan)', amount: '2 tablespoons' },
      { name: 'Turmeric powder', amount: '1/4 teaspoon' },
      { name: 'Yogurt', amount: '1 tablespoon' },
      { name: 'Lemon juice', amount: 'A few drops' },
    ],
    preparation_steps: [
      'Mix gram flour and turmeric in a bowl.',
      'Add yogurt and stir to a creamy consistency.',
      'Add a few drops of lemon juice.',
    ],
    application_steps: [
      'Apply on face and neck.',
      'Leave for 15–20 minutes.',
      'Scrub gently in circular motions while removing.',
      'Rinse with cool water.',
    ],
    frequency: '2–3 times per week',
    ayurvedic_insight: 'The Ubtan (traditional cleansing paste) has been a bridal beauty ritual in India for thousands of years. This combination of besan and haldi is known to bestow "kanti" — natural luminosity.',
    skin_concerns: ['Dark Spots', 'Pigmentation', 'Uneven Tone'],
    skin_types: ['oily', 'combination', 'normal'],
    image_url: null,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r8',
    name: 'Brahmi & Coconut Oil Scalp Massage',
    slug: 'brahmi-coconut-oil-massage',
    description: 'A nourishing scalp and forehead treatment that calms the mind, reduces stress-related skin issues, and promotes healthy hair growth.',
    ingredients: [
      { name: 'Brahmi oil', amount: '2 tablespoons' },
      { name: 'Coconut oil', amount: '1 tablespoon' },
    ],
    preparation_steps: [
      'Mix both oils and warm gently (not hot).',
      'Test temperature on your wrist first.',
    ],
    application_steps: [
      'Part your hair and apply oil along the scalp.',
      'Massage the forehead and temples in circular motions.',
      'Continue massaging for 10–15 minutes.',
      'Leave on for 30 minutes or overnight.',
      'Wash with a mild herbal shampoo.',
    ],
    frequency: '2 times per week',
    ayurvedic_insight: 'Brahmi (Bacopa monnieri) is called "the herb of grace" in Ayurveda. Scalp massage (Shiro Abhyanga) is a key practice in Dinacharya to calm the nervous system and nourish skin from within.',
    skin_concerns: ['Dryness', 'Redness'],
    skin_types: ['dry', 'normal', 'sensitive'],
    image_url: null,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r9',
    name: 'Multani Mitti Oil Control Mask',
    slug: 'multani-mitti-oil-control',
    description: 'A classic Ayurvedic clay mask that absorbs excess oil, tightens pores, and leaves skin feeling fresh and matte.',
    ingredients: [
      { name: 'Multani Mitti (Fuller\'s Earth)', amount: '2 tablespoons' },
      { name: 'Rose water', amount: '2 tablespoons' },
      { name: 'Neem water', amount: '1 tablespoon' },
    ],
    preparation_steps: [
      'Sieve multani mitti to remove lumps.',
      'Add rose water and neem water gradually.',
      'Mix to form a smooth, spreadable paste.',
    ],
    application_steps: [
      'Apply a thick, even layer on face.',
      'Avoid the eye and lip area.',
      'Let it dry completely (15–20 minutes).',
      'Splash water to soften, then rinse off gently.',
    ],
    frequency: '2 times per week',
    ayurvedic_insight: 'Multani Mitti has been used since the Mughal era for its remarkable oil-absorbing and pore-refining properties. It balances excess Kapha in the skin.',
    skin_concerns: ['Oiliness', 'Acne'],
    skin_types: ['oily', 'combination'],
    image_url: null,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r10',
    name: 'Saffron & Honey Glow Serum',
    slug: 'saffron-honey-glow-serum',
    description: 'A luxurious overnight serum that uses saffron to fade pigmentation and honey to lock in deep moisture for radiant morning skin.',
    ingredients: [
      { name: 'Saffron strands', amount: '5–6 strands' },
      { name: 'Raw honey', amount: '1 tablespoon' },
      { name: 'Almond oil', amount: '1 teaspoon' },
    ],
    preparation_steps: [
      'Soak saffron strands in honey overnight (or at least 2 hours).',
      'Add almond oil and mix gently.',
    ],
    application_steps: [
      'Apply a thin layer on clean face before bed.',
      'Massage gently for 2 minutes.',
      'Leave on overnight.',
      'Wash off in the morning with lukewarm water.',
    ],
    frequency: '3–4 times per week',
    ayurvedic_insight: 'Saffron (Kesar) is the most prized beauty ingredient in Ayurveda. Ancient texts describe it as "Varnya" — that which bestows a beautiful complexion.',
    skin_concerns: ['Dark Spots', 'Pigmentation', 'Dryness'],
    skin_types: ['dry', 'normal'],
    image_url: null,
    is_featured: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r11',
    name: 'Tea Tree & Tulsi Spot Treatment',
    slug: 'tea-tree-tulsi-spot-treatment',
    description: 'A targeted treatment for active acne spots that uses the antibacterial power of tulsi and tea tree to reduce breakouts quickly.',
    ingredients: [
      { name: 'Fresh tulsi (basil) leaves paste', amount: '1 tablespoon' },
      { name: 'Tea tree essential oil', amount: '2 drops' },
      { name: 'Aloe vera gel', amount: '1 teaspoon' },
    ],
    preparation_steps: [
      'Crush fresh tulsi leaves into a fine paste.',
      'Mix with aloe vera gel.',
      'Add tea tree oil drops and stir.',
    ],
    application_steps: [
      'Dab directly on acne spots using a clean cotton bud.',
      'Leave on for 30 minutes or overnight.',
      'Rinse gently.',
    ],
    frequency: 'Daily until spots clear',
    ayurvedic_insight: 'Tulsi (Holy Basil) is considered sacred in Ayurveda and is known as "The Queen of Herbs." It purifies blood and has powerful antimicrobial properties.',
    skin_concerns: ['Acne'],
    skin_types: ['oily', 'combination', 'normal'],
    image_url: null,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r12',
    name: 'Cucumber & Mint Cooling Pack',
    slug: 'cucumber-mint-cooling-pack',
    description: 'A refreshing cooling mask perfect for hot weather and sun-exposed skin. Reduces redness, cools inflammation, and hydrates deeply.',
    ingredients: [
      { name: 'Cucumber (grated)', amount: '3 tablespoons' },
      { name: 'Fresh mint leaves (crushed)', amount: '5–6 leaves' },
      { name: 'Aloe vera gel', amount: '1 tablespoon' },
    ],
    preparation_steps: [
      'Grate fresh cucumber and squeeze out excess water.',
      'Crush mint leaves into the cucumber pulp.',
      'Mix in aloe vera gel.',
    ],
    application_steps: [
      'Apply generously on face and neck.',
      'Lie down and relax for 20 minutes.',
      'Rinse with cool water.',
    ],
    frequency: '3 times per week (especially in summer)',
    ayurvedic_insight: 'Cucumber is "Sheeta Virya" (cooling in potency) — ideal for pacifying excess Pitta during hot months. Mint adds a refreshing aromatic dimension to the treatment.',
    skin_concerns: ['Redness', 'Oiliness'],
    skin_types: ['oily', 'combination', 'sensitive', 'normal'],
    image_url: null,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r13',
    name: 'Papaya Enzyme Exfoliator',
    slug: 'papaya-enzyme-exfoliator',
    description: 'A natural enzyme-based exfoliator that dissolves dead skin cells without harsh scrubbing, revealing smoother and brighter skin.',
    ingredients: [
      { name: 'Ripe papaya (mashed)', amount: '2 tablespoons' },
      { name: 'Honey', amount: '1 teaspoon' },
      { name: 'Rice flour', amount: '1 teaspoon' },
    ],
    preparation_steps: [
      'Mash ripe papaya until smooth.',
      'Mix in honey and rice flour for gentle texture.',
    ],
    application_steps: [
      'Apply on clean, damp face.',
      'Leave for 10–15 minutes.',
      'Gently massage in circular motions while rinsing.',
    ],
    frequency: '1–2 times per week',
    ayurvedic_insight: 'Papaya contains papain enzyme, which Ayurveda recognizes as a natural "Lekhana" (scraping) agent that removes dead skin (Mala) without aggravating sensitive skin.',
    skin_concerns: ['Dark Spots', 'Pigmentation', 'Uneven Tone'],
    skin_types: ['normal', 'combination', 'oily'],
    image_url: null,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r14',
    name: 'Manjistha Blood Purifier Tea',
    slug: 'manjistha-blood-purifier-tea',
    description: 'An internal Ayurvedic remedy — a detoxifying tea that purifies blood from within, addressing the root cause of skin issues like acne and pigmentation.',
    ingredients: [
      { name: 'Manjistha powder', amount: '1/2 teaspoon' },
      { name: 'Warm water', amount: '1 cup' },
      { name: 'Honey (optional)', amount: '1 teaspoon' },
    ],
    preparation_steps: [
      'Boil water and let it cool slightly.',
      'Add manjistha powder and stir well.',
      'Add honey for taste if desired.',
    ],
    application_steps: [
      'Drink on an empty stomach in the morning.',
      'Wait 30 minutes before eating breakfast.',
    ],
    frequency: 'Daily for 4–6 weeks',
    ayurvedic_insight: 'Manjistha (Rubia cordifolia) is the premier blood-purifying herb in Ayurveda. Known as "Raktashodhaka," it cleanses the blood channels (Rakta Dhatu) which directly affects skin health.',
    skin_concerns: ['Acne', 'Pigmentation', 'Redness'],
    skin_types: ['oily', 'dry', 'combination', 'normal', 'sensitive'],
    image_url: null,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r15',
    name: 'Ghee & Rose Petal Lip Balm',
    slug: 'ghee-rose-petal-lip-balm',
    description: 'A deeply nourishing lip treatment using clarified butter and rose petals to heal dry, chapped lips overnight.',
    ingredients: [
      { name: 'Pure ghee', amount: '1 teaspoon' },
      { name: 'Dried rose petal powder', amount: '1/4 teaspoon' },
      { name: 'Honey', amount: '1/4 teaspoon' },
    ],
    preparation_steps: [
      'Warm ghee slightly (not hot).',
      'Mix in rose petal powder and honey.',
    ],
    application_steps: [
      'Apply a thick layer on lips before bed.',
      'Leave on overnight.',
      'Gently wipe off in the morning.',
    ],
    frequency: 'Every night',
    ayurvedic_insight: 'Ghee (Ghrita) is considered "Sneha" (the essence of lubrication) in Ayurveda. Combined with rose, it deeply nourishes and restores dry Vata-aggravated skin.',
    skin_concerns: ['Dryness'],
    skin_types: ['dry', 'normal', 'sensitive'],
    image_url: null,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r16',
    name: 'Fenugreek Anti-Acne Paste',
    slug: 'fenugreek-anti-acne-paste',
    description: 'A powerful anti-inflammatory paste that targets cystic acne and prevents future breakouts using fenugreek seeds.',
    ingredients: [
      { name: 'Fenugreek seeds (soaked overnight)', amount: '2 tablespoons' },
      { name: 'Turmeric powder', amount: '1/4 teaspoon' },
      { name: 'Water (for grinding)', amount: 'As needed' },
    ],
    preparation_steps: [
      'Soak fenugreek seeds in water overnight.',
      'Grind to a smooth paste in the morning.',
      'Add turmeric and mix well.',
    ],
    application_steps: [
      'Apply on affected areas or full face.',
      'Leave for 20 minutes.',
      'Rinse with cool water.',
    ],
    frequency: '3 times per week',
    ayurvedic_insight: 'Methi (Fenugreek) is known in Ayurveda for its "Shothahara" (anti-swelling) property. It draws out toxins and reduces the heat (Pitta) that causes inflammatory acne.',
    skin_concerns: ['Acne', 'Redness', 'Oiliness'],
    skin_types: ['oily', 'combination'],
    image_url: null,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r17',
    name: 'Licorice Root Brightening Serum',
    slug: 'licorice-root-brightening-serum',
    description: 'A gentle skin-brightening treatment using licorice root extract to fade dark spots and even skin tone without irritation.',
    ingredients: [
      { name: 'Licorice (Mulethi) powder', amount: '1 teaspoon' },
      { name: 'Lemon juice', amount: '1/2 teaspoon' },
      { name: 'Honey', amount: '1 teaspoon' },
    ],
    preparation_steps: [
      'Mix licorice powder with lemon juice.',
      'Add honey and blend well.',
    ],
    application_steps: [
      'Apply on pigmented areas or full face.',
      'Leave for 15 minutes.',
      'Rinse with lukewarm water.',
    ],
    frequency: '2–3 times per week',
    ayurvedic_insight: 'Yashtimadhu (Licorice/Mulethi) is described as "Varnya" in Charaka Samhita — an herb that naturally brightens complexion. It inhibits melanin production gently.',
    skin_concerns: ['Dark Spots', 'Pigmentation', 'Uneven Tone'],
    skin_types: ['dry', 'normal', 'combination', 'sensitive'],
    image_url: null,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r18',
    name: 'Sesame Oil Abhyanga (Self-Massage)',
    slug: 'sesame-oil-abhyanga',
    description: 'A traditional Ayurvedic self-massage ritual that nourishes dry skin from the outside, calms the nervous system, and promotes healthy circulation.',
    ingredients: [
      { name: 'Warm sesame oil', amount: '3–4 tablespoons' },
    ],
    preparation_steps: [
      'Warm sesame oil in a small bowl (test on wrist for comfort).',
    ],
    application_steps: [
      'Start from the scalp, massage in circular motions.',
      'Move to the face, neck, and ears.',
      'Massage arms and legs with long strokes.',
      'Use circular motions on joints.',
      'Leave oil on for 15–20 minutes.',
      'Take a warm bath or shower.',
    ],
    frequency: 'Daily (morning, before bath)',
    ayurvedic_insight: 'Abhyanga is one of the most important daily practices (Dinacharya) in Ayurveda. Sesame oil (Tila Taila) is considered the king of oils, specifically recommended for Vata constitution.',
    skin_concerns: ['Dryness'],
    skin_types: ['dry', 'normal'],
    image_url: null,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r19',
    name: 'Vetiver & Sandalwood Cooling Mist',
    slug: 'vetiver-sandalwood-cooling-mist',
    description: 'A refreshing face mist that cools inflamed skin, controls redness, and provides an aromatic, calming experience throughout the day.',
    ingredients: [
      { name: 'Vetiver (Khus) water', amount: '50 ml' },
      { name: 'Sandalwood water', amount: '50 ml' },
      { name: 'Rose water', amount: '25 ml' },
    ],
    preparation_steps: [
      'Mix all waters in a clean spray bottle.',
      'Shake well before each use.',
      'Store in the refrigerator for extra cooling effect.',
    ],
    application_steps: [
      'Hold 6–8 inches from face and mist gently.',
      'Can be used over makeup.',
      'Use whenever skin feels warm or irritated.',
    ],
    frequency: '3–4 times daily as needed',
    ayurvedic_insight: 'Vetiver (Ushira) is one of the most powerful Pitta-pacifying herbs in Ayurveda. Combined with sandalwood, this mist creates a "Sheeta" (cooling) therapy for inflamed skin.',
    skin_concerns: ['Redness', 'Oiliness'],
    skin_types: ['sensitive', 'oily', 'combination'],
    image_url: null,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r20',
    name: 'Amla & Honey Hair and Face Mask',
    slug: 'amla-honey-hair-face-mask',
    description: 'A vitamin C-rich treatment that boosts collagen, fights signs of aging, and leaves both skin and hair rejuvenated.',
    ingredients: [
      { name: 'Amla (Indian Gooseberry) powder', amount: '2 tablespoons' },
      { name: 'Honey', amount: '1 tablespoon' },
      { name: 'Yogurt', amount: '1 tablespoon' },
    ],
    preparation_steps: [
      'Mix amla powder with yogurt.',
      'Add honey and stir until smooth.',
    ],
    application_steps: [
      'Apply on face and neck (and hair if desired).',
      'Leave for 20–25 minutes.',
      'Rinse with lukewarm water.',
    ],
    frequency: '2 times per week',
    ayurvedic_insight: 'Amalaki (Amla) is one of the three fruits in Triphala and is the richest natural source of Vitamin C. It\'s classified as a "Rasayana" — a rejuvenating herb that promotes longevity.',
    skin_concerns: ['Dryness', 'Dark Spots', 'Uneven Tone'],
    skin_types: ['dry', 'normal', 'combination'],
    image_url: null,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r21',
    name: 'Cinnamon & Honey Acne Fighter',
    slug: 'cinnamon-honey-acne-fighter',
    description: 'A potent antimicrobial spot mask that combines the warming properties of cinnamon with the healing power of raw honey.',
    ingredients: [
      { name: 'Cinnamon powder', amount: '1/2 teaspoon' },
      { name: 'Raw honey', amount: '1 tablespoon' },
    ],
    preparation_steps: [
      'Mix cinnamon powder into honey until well combined.',
    ],
    application_steps: [
      'Apply only on acne-affected areas.',
      'Leave for 10–15 minutes.',
      'Rinse gently with warm water.',
      'Do a patch test first — cinnamon can be warming.',
    ],
    frequency: '2 times per week',
    ayurvedic_insight: 'Dalchini (Cinnamon) is a Kapha-pacifying spice with strong antimicrobial properties. In Ayurveda, acne is often linked to excess Kapha and Ama (toxins).',
    skin_concerns: ['Acne'],
    skin_types: ['oily', 'combination'],
    image_url: null,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r22',
    name: 'Coconut Oil & Sugar Lip Scrub',
    slug: 'coconut-oil-sugar-lip-scrub',
    description: 'A gentle exfoliating scrub that removes dead skin from lips, leaving them smooth, soft, and naturally pink.',
    ingredients: [
      { name: 'Coconut oil', amount: '1 teaspoon' },
      { name: 'Brown sugar', amount: '1 teaspoon' },
      { name: 'Honey', amount: '1/2 teaspoon' },
    ],
    preparation_steps: [
      'Mix all ingredients in a small bowl.',
    ],
    application_steps: [
      'Apply on lips and scrub gently in circular motions.',
      'Scrub for 1–2 minutes.',
      'Wipe off with a damp cloth.',
      'Apply a lip balm or ghee afterwards.',
    ],
    frequency: '2–3 times per week',
    ayurvedic_insight: 'Coconut (Narikela) oil is considered "Snigdha" (unctuous) and "Sheeta" (cooling) in Ayurveda, making it ideal for gentle skin nourishment.',
    skin_concerns: ['Dryness'],
    skin_types: ['dry', 'normal', 'sensitive'],
    image_url: null,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r23',
    name: 'Camphor & Coconut Redness Relief',
    slug: 'camphor-coconut-redness-relief',
    description: 'A soothing balm that calms irritated, red, and inflamed skin using the cooling properties of camphor blended with coconut oil.',
    ingredients: [
      { name: 'Coconut oil', amount: '2 tablespoons' },
      { name: 'Camphor (Kapoor) - food-grade', amount: '1 small piece' },
    ],
    preparation_steps: [
      'Warm coconut oil slightly.',
      'Dissolve camphor piece in the warm oil.',
      'Let it cool to room temperature.',
    ],
    application_steps: [
      'Apply a thin layer on redness-prone areas.',
      'Massage gently.',
      'Leave on for 20 minutes or overnight.',
      'Rinse with lukewarm water.',
    ],
    frequency: '2–3 times per week',
    ayurvedic_insight: 'Karpura (Camphor) is a powerful "Vedana Sthapana" (pain-relieving) and anti-inflammatory substance in Ayurveda, traditionally used in balms for skin irritation.',
    skin_concerns: ['Redness'],
    skin_types: ['sensitive', 'dry', 'normal'],
    image_url: null,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r24',
    name: 'Lemon & Potato Dark Spot Corrector',
    slug: 'lemon-potato-dark-spot-corrector',
    description: 'A natural bleaching treatment that uses the enzymes in potato and citric acid in lemon to fade stubborn dark spots.',
    ingredients: [
      { name: 'Potato juice (freshly extracted)', amount: '2 tablespoons' },
      { name: 'Lemon juice', amount: '1 teaspoon' },
      { name: 'Honey', amount: '1 teaspoon' },
    ],
    preparation_steps: [
      'Grate raw potato and extract the juice.',
      'Mix with lemon juice and honey.',
    ],
    application_steps: [
      'Apply on dark spots with a cotton pad.',
      'Leave for 15–20 minutes.',
      'Rinse with cool water.',
      'Apply sunscreen afterwards if going outside.',
    ],
    frequency: 'Daily (evening application preferred)',
    ayurvedic_insight: 'While potato is a more modern addition, the principle of using "Lekhana" (lightening) natural acids has roots in Ayurvedic practice. Always protect treated skin from sun exposure.',
    skin_concerns: ['Dark Spots', 'Pigmentation'],
    skin_types: ['oily', 'combination', 'normal'],
    image_url: null,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r25',
    name: 'Oatmeal & Almond Soothing Mask',
    slug: 'oatmeal-almond-soothing-mask',
    description: 'A gentle, nourishing mask perfect for sensitive and dry skin that soothes irritation and provides deep hydration.',
    ingredients: [
      { name: 'Oatmeal (finely ground)', amount: '2 tablespoons' },
      { name: 'Almond powder', amount: '1 tablespoon' },
      { name: 'Milk', amount: '2 tablespoons' },
      { name: 'Honey', amount: '1 teaspoon' },
    ],
    preparation_steps: [
      'Grind oatmeal to a fine powder.',
      'Mix with almond powder.',
      'Add milk and honey, stir to a smooth paste.',
    ],
    application_steps: [
      'Apply on clean face in upward strokes.',
      'Leave for 15–20 minutes.',
      'Rinse with lukewarm water.',
      'Follow with a gentle moisturizer.',
    ],
    frequency: '2–3 times per week',
    ayurvedic_insight: 'Almonds (Vatada) are considered "Brimhana" (nourishing) in Ayurveda. Combined with oats, this mask provides both nourishment and gentle exfoliation.',
    skin_concerns: ['Dryness', 'Redness'],
    skin_types: ['dry', 'sensitive', 'normal'],
    image_url: null,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r26',
    name: 'Charcoal & Tea Tree Deep Cleanse',
    slug: 'charcoal-tea-tree-deep-cleanse',
    description: 'A deep-cleansing mask that draws out impurities, unclogs pores, and prevents blackheads using activated charcoal and tea tree.',
    ingredients: [
      { name: 'Activated charcoal powder', amount: '1 teaspoon' },
      { name: 'Bentonite clay', amount: '1 tablespoon' },
      { name: 'Tea tree oil', amount: '2–3 drops' },
      { name: 'Water', amount: '1–2 tablespoons' },
    ],
    preparation_steps: [
      'Mix charcoal and bentonite clay.',
      'Add water gradually to form a paste.',
      'Add tea tree oil drops and mix.',
    ],
    application_steps: [
      'Apply a thin layer on face, focusing on T-zone.',
      'Leave for 10–15 minutes (do not let it fully dry).',
      'Rinse with warm water.',
      'Follow with a toner and moisturizer.',
    ],
    frequency: '1–2 times per week',
    ayurvedic_insight: 'While charcoal is a modern addition, the principle of using absorptive earth (like clay) for "Shodhana" (purification) of skin is well-established in Ayurveda.',
    skin_concerns: ['Acne', 'Oiliness'],
    skin_types: ['oily', 'combination'],
    image_url: null,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r27',
    name: 'Giloy Immunity & Skin Juice',
    slug: 'giloy-immunity-skin-juice',
    description: 'An internal detox drink that purifies blood, boosts immunity, and addresses skin issues from within using Giloy stem.',
    ingredients: [
      { name: 'Giloy stem juice or powder', amount: '2 tablespoons or 1/2 teaspoon' },
      { name: 'Warm water', amount: '1 glass' },
      { name: 'Honey', amount: '1 teaspoon' },
      { name: 'Lemon juice', amount: '1/2 teaspoon' },
    ],
    preparation_steps: [
      'If using fresh stem: boil 6-inch Giloy stem in water, reduce to half.',
      'If using powder: mix in warm water.',
      'Add honey and lemon juice.',
    ],
    application_steps: [
      'Drink on an empty stomach in the morning.',
      'Wait 30 minutes before breakfast.',
    ],
    frequency: 'Daily for 3–4 weeks',
    ayurvedic_insight: 'Guduchi (Giloy) is called "Amrita" — the divine nectar — in Ayurveda. It\'s a powerful Rasayana that purifies all seven Dhatus (tissue layers) and strengthens immunity.',
    skin_concerns: ['Acne', 'Redness', 'Pigmentation'],
    skin_types: ['oily', 'dry', 'combination', 'normal', 'sensitive'],
    image_url: null,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r28',
    name: 'Rose Petal & Milk Cream Moisturizer',
    slug: 'rose-petal-milk-cream-moisturizer',
    description: 'A rich, natural moisturizer that deeply hydrates dry skin using the softening properties of milk cream and rose.',
    ingredients: [
      { name: 'Fresh milk cream (malai)', amount: '1 tablespoon' },
      { name: 'Rose petal paste', amount: '1 tablespoon' },
      { name: 'Saffron strands', amount: '2–3 strands' },
    ],
    preparation_steps: [
      'Grind fresh rose petals into a paste.',
      'Mix with milk cream.',
      'Add crushed saffron strands.',
    ],
    application_steps: [
      'Apply on clean face and neck.',
      'Massage gently for 5 minutes.',
      'Leave for 20 minutes.',
      'Rinse with lukewarm water.',
    ],
    frequency: '2–3 times per week',
    ayurvedic_insight: 'Milk cream (Malai) is a natural emollient rich in fats that nourishes Vata-type dry skin. Rose petals add "Hridya" (heart-pleasing) aromatic therapy to the experience.',
    skin_concerns: ['Dryness'],
    skin_types: ['dry', 'normal'],
    image_url: null,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r29',
    name: 'Neem Water Daily Face Wash',
    slug: 'neem-water-daily-face-wash',
    description: 'A simple daily cleansing ritual using neem-infused water that keeps acne-prone skin clean, clear, and bacteria-free.',
    ingredients: [
      { name: 'Fresh neem leaves', amount: '10–15 leaves' },
      { name: 'Water', amount: '2 cups' },
    ],
    preparation_steps: [
      'Boil neem leaves in water for 10 minutes.',
      'Let it cool to room temperature.',
      'Strain and store in a clean container.',
      'Can be refrigerated for up to 3 days.',
    ],
    application_steps: [
      'Splash neem water on face as your first step.',
      'Gently pat and massage for 1 minute.',
      'Follow with your regular cleanser if desired.',
    ],
    frequency: 'Daily (morning)',
    ayurvedic_insight: 'Daily use of Neem water is a traditional Dinacharya practice. Nimba (Neem) is described in Bhavaprakasha as the most effective herb for skin purification.',
    skin_concerns: ['Acne', 'Oiliness'],
    skin_types: ['oily', 'combination'],
    image_url: null,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r30',
    name: 'Jasmine & Shea Body Butter',
    slug: 'jasmine-shea-body-butter',
    description: 'A luxurious body moisturizer infused with jasmine fragrance and shea butter for ultra-soft, supple skin.',
    ingredients: [
      { name: 'Shea butter', amount: '3 tablespoons' },
      { name: 'Coconut oil', amount: '1 tablespoon' },
      { name: 'Jasmine essential oil', amount: '5–6 drops' },
      { name: 'Vitamin E oil', amount: '1 teaspoon' },
    ],
    preparation_steps: [
      'Melt shea butter gently using a double boiler.',
      'Mix in coconut oil.',
      'Let it cool slightly, then add jasmine oil and vitamin E.',
      'Whip with a fork or hand mixer until fluffy.',
      'Store in a clean glass jar.',
    ],
    application_steps: [
      'Apply on damp skin after bathing.',
      'Massage in long upward strokes on body.',
      'Focus on dry areas: elbows, knees, heels.',
    ],
    frequency: 'Daily after bath',
    ayurvedic_insight: 'Jasmine (Jati) is considered a "Hridya" (heart-pleasing) flower in Ayurveda. Its aroma calms Pitta and Vata, while the rich butters deeply nourish dry (Vata) skin.',
    skin_concerns: ['Dryness'],
    skin_types: ['dry', 'normal', 'sensitive'],
    image_url: null,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r31',
    name: 'Tomato & Curd Tan Removal Pack',
    slug: 'tomato-curd-tan-removal',
    description: 'A natural de-tanning mask that removes sun tan, brightens skin, and restores your natural complexion using tomato and curd.',
    ingredients: [
      { name: 'Ripe tomato pulp', amount: '2 tablespoons' },
      { name: 'Fresh curd (yogurt)', amount: '1 tablespoon' },
      { name: 'Oatmeal (ground)', amount: '1 teaspoon' },
    ],
    preparation_steps: [
      'Extract tomato pulp by blending and straining.',
      'Mix with curd and oatmeal powder.',
    ],
    application_steps: [
      'Apply on sun-tanned areas — face, neck, arms.',
      'Leave for 20 minutes.',
      'Gently scrub in circular motions while rinsing.',
      'Follow with moisturizer and sunscreen.',
    ],
    frequency: '3 times per week',
    ayurvedic_insight: 'Tomato\'s natural acidity acts as a gentle "Varnya" (complexion enhancer), while curd provides lactic acid exfoliation — a combination that aligns with Ayurvedic principles of natural skin renewal.',
    skin_concerns: ['Dark Spots', 'Uneven Tone', 'Pigmentation'],
    skin_types: ['oily', 'combination', 'normal'],
    image_url: null,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'r32',
    name: 'Aloe Vera Overnight Recovery Gel',
    slug: 'aloe-vera-overnight-recovery',
    description: 'A simple overnight healing gel that repairs sun damage, soothes irritation, and deeply hydrates skin while you sleep.',
    ingredients: [
      { name: 'Fresh aloe vera gel', amount: '2 tablespoons' },
      { name: 'Vitamin E capsule', amount: '1 capsule' },
      { name: 'Rose water', amount: '1 teaspoon' },
    ],
    preparation_steps: [
      'Extract fresh aloe gel and blend until smooth.',
      'Pierce vitamin E capsule and add the oil.',
      'Mix in rose water.',
    ],
    application_steps: [
      'Apply a thin, even layer on clean face before bed.',
      'Let it absorb naturally.',
      'Wash off in the morning with lukewarm water.',
    ],
    frequency: 'Every night',
    ayurvedic_insight: 'Kumari (Aloe Vera) is a "Tridosha Shamaka" — it balances all three doshas. Its cooling, healing, and moisturizing properties make it a universal skin remedy in Ayurveda.',
    skin_concerns: ['Dryness', 'Redness', 'Acne'],
    skin_types: ['oily', 'dry', 'combination', 'normal', 'sensitive'],
    image_url: null,
    is_featured: true,
    created_at: '2024-01-01T00:00:00Z',
  },
];

// ============================================================
// DAILY TIPS (30+ entries)
// ============================================================

export const MOCK_DAILY_TIPS: DailyTip[] = [
  { id: 't1', content: 'Apply rose water to refresh your skin every morning. It balances your skin\'s pH naturally. 🌹', category: 'hydration', display_order: 1, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't2', content: 'Massage your face with warm sesame oil before bathing to nourish dry skin. This ancient Abhyanga ritual is the ultimate self-care. 🧴', category: 'moisturizing', display_order: 2, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't3', content: 'Drink a glass of warm water with lemon first thing in the morning to flush toxins and boost your skin\'s natural glow. 🍋', category: 'detox', display_order: 3, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't4', content: 'Never skip sunscreen! Even on cloudy days, UV rays can cause dark spots and premature aging. Protect your skin naturally. ☀️', category: 'protection', display_order: 4, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't5', content: 'Try to sleep by 10 PM. In Ayurveda, the Pitta period (10 PM–2 AM) is when your body repairs and rejuvenates skin cells. 🌙', category: 'lifestyle', display_order: 5, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't6', content: 'Apply aloe vera gel on your face after sun exposure. It soothes inflammation and helps repair sun-damaged skin. 🌿', category: 'healing', display_order: 6, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't7', content: 'Eat more fruits rich in Vitamin C — amla, oranges, guavas. They boost collagen and fight free radical damage. 🍊', category: 'diet', display_order: 7, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't8', content: 'Use a silk or satin pillowcase to reduce friction on your skin while sleeping. It prevents wrinkles and acne breakouts. 🛏️', category: 'lifestyle', display_order: 8, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't9', content: 'Rub an ice cube wrapped in cloth on your face for 1 minute. This simple technique reduces puffiness and tightens pores. 🧊', category: 'routine', display_order: 9, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't10', content: 'Practice Pranayama (breathing exercises) for 5 minutes daily. Better oxygen flow = healthier, more radiant skin. 🧘', category: 'lifestyle', display_order: 10, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't11', content: 'Avoid touching your face frequently. Your hands carry bacteria that can cause breakouts and irritation. 🙌', category: 'hygiene', display_order: 11, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't12', content: 'Add turmeric to your meals or milk. Haldi has anti-inflammatory properties that work from the inside out. 🥛', category: 'diet', display_order: 12, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't13', content: 'Drink at least 8 glasses of water daily. Hydration is the foundation of healthy, plump, and glowing skin. 💧', category: 'hydration', display_order: 13, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't14', content: 'Apply honey on your lips before bed for naturally soft, pink lips by morning. Raw honey is the best natural moisturizer. 🍯', category: 'moisturizing', display_order: 14, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't15', content: 'Replace your regular tea with green tea. It\'s loaded with antioxidants that fight skin aging and reduce inflammation. 🍵', category: 'diet', display_order: 15, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't16', content: 'Clean your phone screen daily. It presses against your cheek and can transfer bacteria that cause jawline acne. 📱', category: 'hygiene', display_order: 16, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't17', content: 'Try a weekly steam facial with neem leaves. Steam opens pores, and neem purifies — a powerful combination for clear skin. 🌿', category: 'routine', display_order: 17, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't18', content: 'Reduce sugar and dairy if you have acne-prone skin. These foods can trigger excess oil production and breakouts. 🍬', category: 'diet', display_order: 18, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't19', content: 'Always remove makeup before sleeping. Sleeping with makeup clogs pores and leads to dull, tired-looking skin. 🧹', category: 'hygiene', display_order: 19, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't20', content: 'Practice "Nasya" — apply 2 drops of warm ghee or sesame oil inside each nostril. It moisturizes dry nasal passages and benefits facial skin. 👃', category: 'ayurveda', display_order: 20, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't21', content: 'Exercise for at least 30 minutes daily. Sweating helps flush toxins and brings a natural glow to your skin. 🏃', category: 'lifestyle', display_order: 21, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't22', content: 'Include ghee in your diet. In Ayurveda, ghee is considered the best fat for nourishing skin from within. 🧈', category: 'diet', display_order: 22, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't23', content: 'Wash your face with lukewarm water, not hot. Hot water strips natural oils and can make skin dry and irritated. 🚿', category: 'routine', display_order: 23, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't24', content: 'Apply coconut oil on your body 15 minutes before shower. It locks in moisture and makes skin silky smooth. 🥥', category: 'moisturizing', display_order: 24, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't25', content: 'Eat a handful of soaked almonds daily. Almonds are rich in Vitamin E — essential for skin repair and protection. 🌰', category: 'diet', display_order: 25, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't26', content: 'Practice digital detox for 1 hour before bed. Blue light from screens can disrupt sleep and accelerate skin aging. 📵', category: 'lifestyle', display_order: 26, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't27', content: 'Use cucumber slices on your eyes for 10 minutes when they feel tired. It reduces puffiness and dark circles naturally. 🥒', category: 'routine', display_order: 27, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't28', content: 'Change your pillowcase every 2–3 days. Oil, dirt, and bacteria accumulate and can cause acne while you sleep. 🛌', category: 'hygiene', display_order: 28, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't29', content: 'Add fresh curry leaves to your meals. They\'re rich in antioxidants that prevent premature skin aging. 🌿', category: 'diet', display_order: 29, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't30', content: 'Smile more! It\'s the best natural exercise for facial muscles and helps you look youthful and radiant. 😊', category: 'lifestyle', display_order: 30, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't31', content: 'Apply a paste of fresh tulsi (basil) leaves to acne spots. Tulsi is nature\'s antibiotic for the skin. 🌿', category: 'healing', display_order: 31, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 't32', content: 'Mix a pinch of turmeric in your face wash. It brightens skin and fights bacteria with every cleanse. ✨', category: 'routine', display_order: 32, display_date: null, is_active: true, created_at: '2024-01-01T00:00:00Z' },
];

// ============================================================
// MOCK SCAN RESULT (for demo/fallback)
// ============================================================

export const MOCK_SCAN_RESULT: Omit<ScanResult, 'id' | 'user_id' | 'image_url' | 'created_at'> = {
  summary: 'Oily Skin with Mild Acne',
  skin_types: ['Oily', 'Acne-Prone'],
  severity: 'mild',
  causes: [
    { icon: '🍔', text: 'Your diet may include excess processed or fried foods, which can increase oil production and clog pores.' },
    { icon: '😴', text: 'Irregular sleep patterns may be disrupting your skin\'s natural repair cycle.' },
    { icon: '😰', text: 'Stress can elevate cortisol levels, leading to increased sebum production and breakouts.' },
    { icon: '🌤️', text: 'Environmental factors like humidity and pollution can contribute to clogged pores and oiliness.' },
    { icon: '💧', text: 'Not drinking enough water throughout the day can cause your skin to overcompensate by producing more oil.' },
  ] as ScanCause[],
  remedies: [
    {
      name: 'Neem Face Wash',
      ingredient: 'Neem',
      what_to_use: 'Neem leaf paste or neem-based cleanser',
      how_to_apply: [
        'Wet your face with lukewarm water.',
        'Apply neem paste gently in circular motions.',
        'Focus on oily areas — forehead, nose, chin.',
        'Rinse with cool water and pat dry.',
      ],
      how_often: '3 times per week',
    },
    {
      name: 'Aloe Vera Moisturizer',
      ingredient: 'Aloe Vera',
      what_to_use: 'Fresh aloe vera gel from the leaf',
      how_to_apply: [
        'Extract fresh gel from an aloe leaf.',
        'Apply a thin layer on clean face.',
        'Let it absorb naturally for 5 minutes.',
        'No need to rinse — it acts as a light moisturizer.',
      ],
      how_often: 'Daily (morning & evening)',
    },
    {
      name: 'Turmeric Spot Treatment',
      ingredient: 'Turmeric',
      what_to_use: 'Turmeric paste mixed with honey',
      how_to_apply: [
        'Mix 1/4 tsp turmeric with 1 tsp raw honey.',
        'Dab on active acne spots with a clean finger.',
        'Leave for 15–20 minutes.',
        'Rinse gently with warm water.',
      ],
      how_often: '2–3 times per week',
    },
  ] as ScanRemedy[],
  prevention_tips: [
    { icon: '💧', text: 'Drink at least 8 glasses of water daily to keep your skin hydrated from within.' },
    { icon: '🌙', text: 'Aim to sleep by 10 PM — your skin repairs itself during the Pitta hours (10 PM–2 AM).' },
    { icon: '🥗', text: 'Include more fresh vegetables, fruits, and whole grains in your diet. Reduce fried and processed foods.' },
    { icon: '☀️', text: 'Apply natural sunscreen or aloe vera before going outdoors to protect against UV damage.' },
    { icon: '🧘', text: 'Practice 5 minutes of deep breathing or meditation daily to manage stress levels.' },
  ] as PreventionTip[],
  raw_analysis: null,
};

// Helper to get today's tip
export function getTodaysTip(): DailyTip {
  const dayOfYear = Math.floor(
    (Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) / (1000 * 60 * 60 * 24)
  );
  const index = dayOfYear % MOCK_DAILY_TIPS.length;
  return MOCK_DAILY_TIPS[index];
}

// Helper to filter remedies
export function filterRemedies(
  remedies: Remedy[],
  options: { concern?: string; skinType?: string; search?: string }
): Remedy[] {
  let filtered = [...remedies];

  if (options.concern && options.concern !== 'All') {
    filtered = filtered.filter((r) =>
      r.skin_concerns.some((c) => c.toLowerCase() === options.concern!.toLowerCase())
    );
  }

  if (options.skinType) {
    filtered = filtered.filter((r) =>
      r.skin_types.includes(options.skinType!)
    );
  }

  if (options.search) {
    const term = options.search.toLowerCase();
    filtered = filtered.filter(
      (r) =>
        r.name.toLowerCase().includes(term) ||
        r.description.toLowerCase().includes(term) ||
        r.ingredients.some((i) => i.name.toLowerCase().includes(term))
    );
  }

  return filtered;
}
